steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '.',
        '-t',
        'gcr.io/$PROJECT_ID/mdblinks-admin-staging:$SHORT_SHA',
        '-f',
        'Dockerfile',
        '--build-arg',
        'REACT_APP_AUTH0_DOMAIN=${_REACT_APP_AUTH0_DOMAIN}',
        '--build-arg',
        'REACT_APP_AUTH0_CLIENTID=${_REACT_APP_AUTH0_CLIENTID}',
        '--build-arg',
        'REACT_APP_AUTH0_AUDIENCE=${_REACT_APP_AUTH0_AUDIENCE}',
        '--build-arg',
        'REACT_APP_REALM_APP_ID=${_REACT_APP_REALM_APP_ID}',
        '--build-arg',
        'REACT_APP_LANDING_URL=${_REACT_APP_LANDING_URL}',

      ]

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mdblinks-admin-staging:$SHORT_SHA']

  # Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mdblinks-admin-staging'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--image=gcr.io/${PROJECT_ID}/mdblinks-admin-staging:$SHORT_SHA'
      - '--port=8080'

options:
  logging: CLOUD_LOGGING_ONLY