steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'landing'
    args:
      [
        'build',
        '.',
        '-t',
        'gcr.io/$PROJECT_ID/mdblink-$BRANCH_NAME-landing:$SHORT_SHA',
        '-f',
        'Dockerfile',
        '--build-arg',
        'REACT_APP_API_URL=${_REACT_APP_API_URL}'
      ]

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mdblink-$BRANCH_NAME-landing:$SHORT_SHA']

  # Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mdblink-${BRANCH_NAME}-landing'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--image=gcr.io/${PROJECT_ID}/mdblink-${BRANCH_NAME}-landing:$SHORT_SHA'
      - '--port=8080'

options:
  logging: CLOUD_LOGGING_ONLY