steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'redirector'
    args:
      [
        'build',
        '.',
        '-t',
        'gcr.io/$PROJECT_ID/mdblink-staging-redirector:$SHORT_SHA',
        '-f',
        'Dockerfile'
      ]

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mdblink-staging-redirector:$SHORT_SHA']

  # Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mdblink-staging-redirector'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--image=gcr.io/${PROJECT_ID}/mdblink-staging-redirector:$SHORT_SHA'
      - '--port=8080'

options:
  logging: CLOUD_LOGGING_ONLY